name: Build Docker Image (Traditional Chinese)

on:
  push:
    tags:
      - "v*-zh-tw"
    branches:
      - main
  workflow_dispatch:

jobs:
  build_docker_image:
    name: Build Docker Image (Traditional Chinese)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            charles0568/gpt-load-zh-tw
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=raw,value=zh-tw-latest,enable={{is_default_branch}}
            type=raw,value=zh-tw-{{sha}},enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name || github.sha }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: charles0568/gpt-load-zh-tw
          short-description: "GPT-Load 繁體中文版 - 高效能 AI 介面透明代理服務"
          readme-filepath: ./README.md
